apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:waleedmagdy/devops_project.git
    targetRevision: <specific_revision_or_tag>
    path: manifests/observability
  destination:
    server: https://kubernetes.default.svc
    namespace: <specific_namespace>
  syncPolicy:
    automated: {}